apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "queryService.fullname" . }}
  labels:
    {{- include "queryService.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "queryService.fullname" . }}
  replicas: {{ .Values.queryService.replicaCount }}
  selector:
    matchLabels:
      {{- include "queryService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "queryService.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "queryService.serviceAccountName" . }}
      {{- if .Values.queryService.initContainers.init.enabled }}
      initContainers:
        - name: {{ include "otelCollectorMetrics.fullname" . }}-init
          image: {{ include "otelCollectorMetrics.initContainers.init.image" . }}
          imagePullPolicy: {{ .Values.otelCollectorMetrics.initContainers.init.image.pullPolicy }}
          command:
            - sh
            - -c
            - until wget --spider -q {{ include "clickhouse.httpUrl" $ }}{{ .endpoint }}; do echo -e "{{ .waitMessage }}"; sleep {{ .delay }}; done; echo -e "{{ .doneMessage }}";
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
        {{- with .Values.queryService.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.queryService.securityContext | nindent 12 }}
          image: {{ template "queryService.image" . }}
          imagePullPolicy: {{ .Values.queryService.image.pullPolicy }}
          args: ["-config=/root/config/prometheus.yml"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: DruidClientUrl
            value: {{ .Values.queryService.configVars.druidClientUrl }}
          - name: DruidDatasource
            value: {{ .Values.queryService.configVars.druidDatasource }}
          - name: STORAGE
            value: {{ .Values.queryService.configVars.storage }}
          - name: ClickHouseUrl
            {{ if hasKey .Values.queryService.configVars "clickHouseUrl" -}}
            value: {{ .Values.queryService.configVars.clickHouseUrl }}
            {{- else -}}
            value: tcp://{{ include "clickhouse.url" . }}
            {{- end }}
          - name: ALERTMANAGER_API_PREFIX
            value: http://{{ include "alertmanager.servicename" . }}:{{ include "alertmanager.port" . }}/api/
          - name: GODEBUG
            value: {{ .Values.queryService.configVars.goDebug }}
          - name: POSTHOG_API_KEY
            value: {{ .Values.queryService.configVars.posthogApiKey }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - name: prometheus
            mountPath: /root/config
          - name: signoz-db
            mountPath: /var/lib/signoz/
          - name: dashboards
            mountPath: /root/config/dashboards
          resources:
            {{- toYaml .Values.queryService.resources | nindent 12 }}
      {{- with .Values.queryService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.queryService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.queryService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: prometheus
        configMap:
          name: prometheus-config
      - name: dashboards
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: signoz-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
