{{- if .Values.otelDeployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otelDeployment.serviceAccountName" . }}
  labels:
    {{- include "otelDeployment.labels" . | nindent 4 }}
  {{- with .Values.otelDeployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
