apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otelCollectorMetrics.fullname" . }}-{{ include "signoz.namespace" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "otelCollectorMetrics.fullname" . }}-{{ include "signoz.namespace" . }}
subjects:
  - name: {{ include "otelCollectorMetrics.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ include "signoz.namespace" . }}
