{{- $clickhousehostport := print (include "clickhouse.servicename" .) ":" .Values.clickhouse.service.tcpPort -}}
{{- $prometheusMetricsTarget := print (include "otelCollector.fullname" .) ":" .Values.otelCollector.ports.prometheusExportedMetrics -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelCollectorMetrics.fullname" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
data:
  otel-collector-metrics-config.yaml: |-
    {{- with .Values.otelCollectorMetrics.config -}}
    {{- with .receivers }}
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus: # Data sources: metrics
        config:
          scrape_configs:
            - job_name: {{ .prometheus.jobName }}
              scrape_interval: {{ .prometheus.scrapeInterval }}
              static_configs:
                {{- if .prometheus.prometheusOverride -}}
                {{- $prometheusMetricsTarget = print .prometheus.prometheusOverride.host ":" .prometheus.prometheusOverride.port }}
                {{- end }}
                - targets: ["{{ $prometheusMetricsTarget }}"]
    {{- end -}}
    {{- with .processors }}
    processors:
      batch:
        send_batch_size: {{ .batch.sendBatchSize }}
        timeout: {{ .batch.timeout | quote  }}
      memory_limiter:
        ballast_size_mib: {{ .memoryLimiter.ballastSizeMib }}
        limit_mib: {{ .memoryLimiter.limitMib }}
        spike_limit_mib: {{ .memoryLimiter.spikeLimitMib }}
        check_interval: {{ .memoryLimiter.checkInterval | quote }}
      {{- if .queuedRetry }}
      queued_retry:
        num_workers: {{ .queuedRetry.numWorkers }}
        queue_size: {{ .queuedRetry.queueSize }}
      {{- end -}}
    {{- end }}
    extensions:
      health_check:
        {{- toYaml .extensions.healthCheck | nindent 8 }}
      zpages:
        {{- toYaml .extensions.zpages | nindent 8 }}
    {{- with .exporters }}
    exporters:
      clickhousemetricswrite:
        {{- with .clickhousemetricswrite.endpoint -}}
        {{- if .clickhouseOverride -}}
        {{- $clickhousehostport = print .clickhouseOverride.host ":" .clickhouseOverride.port }}
        {{- end }}
        {{- $endpointUrl := print $clickhousehostport "?database=" .database "&username=" .username "&password=" .password }}
        endpoint: tcp://{{ $endpointUrl }}
        {{- end -}}
    {{- end -}}
    {{- with .service }}
    service:
      extensions:
        {{- toYaml .extensions | nindent 8 }}
      pipelines:
        {{- with .pipelines.metrics }}
        metrics:
          receivers: {{- toYaml .receivers | nindent 12 }}
          processors: {{- toYaml .processors | nindent 12 }}
          exporters: {{- toYaml .exporters | nindent 12 }}
        {{- end -}}
    {{- end }}
    {{- end }}
