apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otelCollectorMetrics.fullname" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otelCollectorMetrics.selectorLabels" . | nindent 6 }}
  minReadySeconds: {{ .Values.otelCollectorMetrics.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.otelCollectorMetrics.progressDeadlineSeconds }}
  replicas: {{ .Values.frontend.replicaCount }} # adjust replica count to your own requirements
  template:
    metadata:
      labels:
        {{- include "otelCollectorMetrics.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.otelCollectorMetrics.initContainers.init.enabled }}
        - name: {{ include "otelCollectorMetrics.fullname" . }}-init
          image: {{ include "otelCollectorMetrics.initContainers.init.image" . }}
          imagePullPolicy: {{ .Values.otelCollectorMetrics.initContainers.init.image.pullPolicy }}
          {{- with .Values.otelCollectorMetrics.initContainers.init.command }}
          command:
            {{- $clickhousehost := print (include "clickhouse.servicename" $) -}}
            {{- if hasKey . "clickhouseHostOverride" -}}
            {{- $clickhousehost = .clickhouseHostOverride -}}
            {{- end }}
            - sh
            - -c
            - until wget --spider -q {{ $clickhousehost }}:{{ .port }}/{{ .endpoint }}; do echo -e "{{ .waitMessage }}"; sleep {{ .delay }}; done; echo -e "{{ .doneMessage }}";
          {{- end -}}
        {{- end }}
      containers:
      - name: {{ template "otelCollectorMetrics.fullname" . }}
        image: {{ .Values.otelCollectorMetrics.image.repository }}:{{ .Values.otelCollectorMetrics.image.tag }}
        imagePullPolicy: {{ .Values.otelCollectorMetrics.image.pullPolicy }}
        command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-metrics-config.yaml"
          - "--mem-ballast-size-mib={{ .Values.otelCollectorMetrics.ballastSizeMib }}"
        volumeMounts:
        - name: otel-collector-metrics-config-vol
          mountPath: /conf
        # - name: otel-collector-secrets
        #   mountPath: /secrets
        {{- if .Values.otelCollector.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            port: {{ .Values.otelCollector.livenessProbe.port }}
            path: {{ .Values.otelCollector.livenessProbe.path }}
          initialDelaySeconds: {{ .Values.otelCollector.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.otelCollector.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.otelCollector.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.otelCollector.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.otelCollector.livenessProbe.failureThreshold }}
        {{- else if .Values.otelCollector.customLivenessProbe }}
        livenessProbe: {{- toYaml .Values.otelCollector.customLivenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.otelCollector.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            port: {{ .Values.otelCollector.readinessProbe.port }}
            path: {{ .Values.otelCollector.readinessProbe.path }}
          initialDelaySeconds: {{ .Values.otelCollector.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.otelCollector.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.otelCollector.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.otelCollector.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.otelCollector.readinessProbe.failureThreshold }}
        {{- else if .Values.otelCollector.customReadinessProbe }}
        readinessProbe: {{- toYaml .Values.otelCollector.customReadinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.otelCollectorMetrics.resources | nindent 10 }}
      volumes:
        - name: otel-collector-metrics-config-vol
          configMap:
            name: {{ include "otelCollectorMetrics.fullname" . }}
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
