apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelCollectorMetrics.fullname" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.otelCollectorMetrics.serviceType }}
  ports:
  - name: otlp-grpc
    port: {{ .Values.otelCollector.ports.otelGrpcReceiver }}
  - name: otlp-http
    port: {{ .Values.otelCollector.ports.otelHttpReceiver }}
  - name: otlp-grpc-legacy
    port: {{ .Values.otelCollector.ports.otelGrpcLegacyReceiver }}
  - name: otlp-http-legacy
    port: {{ .Values.otelCollector.ports.otelHttpLegacyReceiver }}
  - name: jaeger-grpc
    port: {{ .Values.otelCollectorMetrics.ports.jaegerGrpcReceiver }}
  - name: jaeger-thrift-http
    port: {{ .Values.otelCollectorMetrics.ports.jaegerHttpReceiver }}
  - name: zipkin
    port: {{ .Values.otelCollectorMetrics.ports.zipkinReceiver }}
  - name: metrics
    port: {{ .Values.otelCollectorMetrics.ports.queryingMetrics }}
  selector:
    {{- include "otelCollectorMetrics.selectorLabels" . | nindent 4 }}