apiVersion: v2
name: clickhouse
description: A Helm chart for ClickHouse
type: application
version: 9.1.0
appVersion: "21.7"
dependencies:
  - name: zookeeper
    repository: "https://charts.bitnami.com/bitnami"
    version: 6.0.0
