apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otelCollector.fullname" . }}-{{ include "signoz.namespace" . }}
  namespace: {{ include "signoz.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "otelCollector.fullname" . }}-{{ include "signoz.namespace" . }}
subjects:
  - name: {{ include "otelCollector.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ include "signoz.namespace" . }}
