apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelCollector.fullname" . }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |-
    {{- with .Values.otelCollector.config -}}
    {{- with .receivers }}
    receivers:
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: {{ .otlpSpanmetrics.protocols.grpc.endpoint }}
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_http:
    {{- end -}}
    {{- with .processors }}
    processors:
      batch:
        send_batch_size: {{ .batch.sendBatchSize }}
        timeout: {{ .batch.timeout }}
      signozspanmetrics/prometheus:
        metrics_exporter: {{ .signozSpanmetricsPrometheus.metricsExporter }}
        latency_histogram_buckets:
          {{- toYaml .signozSpanmetricsPrometheus.latencyHistogramBuckets | nindent 10 }}
        dimensions_cache_size: {{ .signozSpanmetricsPrometheus.dimensionsCacheSize }}
      memory_limiter:
        {{- toYaml .memory_limiter | nindent 8 }}
      {{- if .queuedRetry }}
      queued_retry:
        num_workers: {{ .queuedRetry.numWorkers }}
        queue_size: {{ .queuedRetry.queueSize }}
        retry_on_failure: {{ .queuedRetry.retryOnFailure }}
      {{- end -}}
    {{- end }}
    extensions:
      health_check:
        {{- toYaml .extensions.healthCheck | nindent 8 }}
      zpages:
        {{- toYaml .extensions.zpages | nindent 8 }}
    {{- with .exporters }}
    exporters:
      clickhouse:
        {{ if .clickhouse.datasource.clickhouseUrlOverride -}}
        datasource: {{ .clickhouse.datasource.clickhouseUrlOverride }}
        {{- else -}}
        datasource: tcp://{{ include "clickhouse.url" $ }}
        {{- end }}
      clickhousemetricswrite:
        {{ if .clickhousemetricswrite.endpoint.clickhouseUrlOverride -}}
        endpoint: {{ .clickhousemetricswrite.endpoint.clickhouseUrlOverride }}
        {{- else -}}
        endpoint: tcp://{{ include "clickhouse.metricsUrl" $ }}
        {{- end }}
        resource_to_telemetry_conversion:
          enabled: {{ .clickhousemetricswrite.resourceToTelemetryConversion.enabled }}
      prometheus:
        endpoint: {{ .prometheus.endpoint }}
    {{- end -}}
    {{- with .service }}
    service:
      extensions:
        {{- toYaml .extensions | nindent 8 }}
      {{- with .pipelines }}
      pipelines:
        traces:
          receivers: {{- toYaml .traces.receivers | nindent 12 }}
          processors: {{- toYaml .traces.processors | nindent 12 }}
          exporters: {{- toYaml .traces.exporters | nindent 12 }}
        metrics:
          receivers: {{- toYaml .metrics.receivers | nindent 12 }}
          processors: {{- toYaml .metrics.processors | nindent 12 }}
          exporters: {{- toYaml .metrics.exporters | nindent 12 }}
        metrics/spanmetrics:
          receivers: {{- toYaml .metricsspanmetrics.receivers | nindent 12 }}
          exporters: {{- toYaml .metricsspanmetrics.exporters | nindent 12 }}
      {{- end -}}
    {{- end -}}
    {{- end }}