apiVersion: v2
name: otel-collector
description: Otel Collector for SigNoz
type: application
version: 0.0.1
appVersion: "0.26.1"
icon: https://signoz.io/img/SigNozLogo-orange.svg
dependencies:
  - name: clickhouse
    repository: "file://../clickhouse"
    version: 9.1.0
maintainers:
  - name: signoz
    email: hello@signoz.io
  - name: prashant
    email: prashant@signoz.io
