apiVersion: v2
name: signoz
version: 0.3.2
appVersion: "0.11.0"
description: SigNoz Observability Platform Helm Chart
type: application
home: https://signoz.io/
icon: https://signoz.io/img/SigNozLogo-orange.svg
keywords:
  - SigNoz
  - opentelemetry
  - apm
  - monitoring
  - distributed tracing
sources:
  - https://github.com/signoz/charts/
  - https://github.com/signoz/signoz
  - https://github.com/signoz/alertmanager
  - https://github.com/signoz/opentelemetry-collector-contrib
dependencies:
  - name: clickhouse
    repository: "https://signoz.github.io/charts"
    condition: clickhouse.enabled
    version: 23.5.2
maintainers:
  - name: SigNoz
    email: hello@signoz.io
    url: https://signoz.io
  - name: prashant-shahi
    email: prashant@signoz.io
    url: https://prashantshahi.dev
